# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoadingManagerExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoadingManagerExample

  pod 'LoadingManager', :path => '../'
  pod 'SnapKit', '~> 4.0'

end
